name: ClearHeadToDo
version: "0.1.0"
about: can be used to manage every part of your productive life!
author: Darrion Burgess <darrionburgess@gmail.com>

subcommands:
        - list_tasks:
                about: prints all tasks in the list
                alias: lt
        - create_task:
                about: creates a new task in the task list. defaults to low priority named test task.
                alias: create
        - rename_task:
                about: removes a given task from the list permanantly, only do this if you're sure you don't want the task anymore.
                alias: rename
                args:
                        - index:
                                required: true
                        - new_name:
                                required: true
                                multiple: true
        - reprioritize:
                about: changes task priority to the given priority, duplicates are rejected
                alias: rp
                args:
                        - index: 
                                required: true
                        - new_priority:
                                required: true
        - complete_task:
                about: completes a given task, using the required index argument, use "list_task" to see index numbers.
                alias: complete
                args:
                        - index:
                                required: true
        - remove_task:
                about: removes a given task from the list permanantly, only do this if you're sure you don't want the task anymore.
                alias: delete
                args:
                        - index:
                                required: true
